
#spring.datasource:
#  url: jdbc:h2:mem:testdb
#  username: sa
#  password:


spring:
  jpa:
    show-sql: true
#    database-platform: org.
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/ppmtool
    username: pguser
    password: pguser